import { Injectable } from '@angular/core';

import { Course } from './course';

@Injectable()
export class CourseService {
  private courses: Course[] = [
    new Course('1. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('2. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[3] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('3. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('4. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('5. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('6. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('7. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('8. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('9. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('24. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('44. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[20] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('1. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('1. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('1. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('1. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('1. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('1. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('1. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('1. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('1. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('1. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('1. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('1. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('1. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('1. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('1. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('1. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('1. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
    new Course('1. Angular Basics', 'Some Lecturer', 'Angular (commonly referred to as "Angular 5" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.'),
    new Course('1. NativeScript Basics', 'Some Lecturer', 'NativeScript is an open-source framework to develop apps on the Apple iOS and Android platforms. It was originally conceived and developed by Progress.[2] NativeScript apps are built using JavaScript, or by using any language that transpiles to JavaScript, such as TypeScript. NativeScript directly supports the Angular framework [3] and supports the Vue framework via a community-developed plugin [4]. Mobile applications built with NativeScript result in fully native apps, which use the same APIs as if they were developed in Xcode or Android Studio.[5] Additionally, software developers can re-purpose third-party libraries from Cocoapods, Android Arsenal, Maven, and npm.js in their mobile applications without the need for wrappers.'),
    new Course('1. React Basics', 'Some Lecturer', 'In computing, React (sometimes React.js or ReactJS) is a JavaScript library[2] for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations.[3][4][5] React can be used in the development of single-page applications and mobile applications. It aims primarily to provide speed, simplicity, and scalability. As a user interface library, React is often used in conjunction with other libraries such as Redux.'),
    new Course('1. Vue Basics', 'Some Lecturer', 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source JavaScript framework for building user interfaces.[4] Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications.'),
  ];

  constructor() { }

  getAll() {
    return this.courses;
  }

  getCourse(name) {
    const course = this.courses.find(course => course.name === name);
    return course;
  }

  addCourse(course: Course) {
    this.courses.push(course);
  }

  removeCourse(course: Course) {
    const index = this.courses.findIndex(c => c === course);
    this.courses.splice(index, 1);
  }

  editCourse(edittedCourse: Course, name: string) {
    const index = this.courses.findIndex(c => c.name === name);
    this.courses[index] = edittedCourse; 
  }
}
